spring:
  application:
    name: zuul
server:
  port: 8080

zuul:
  routes:
    api-config:
      path: /configserver/**
      serviceId:  configserver
    api-admin:
      path: /admin/**
      serviceId: admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
logging:
  path: ./logs